server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: SAMPLE-APP

swagger:
  basePackage: com.neatcode.serviceRegistry
  path: /api/.*
  title: Registry Demo
  description: REST API to interact with Demo Application
  version: 1.0.0-SNAPSHOT
